### PR TITLE
LPS-185318

### PR DESCRIPTION
**Pull request by kevhlee**
Hi @michaelmdelcavalcanti,

There were some problems regarding the pull request you sent: <https://github.com/kevhlee/liferay-portal/pull/69>. Mainly, trying to find variable declarations line-by-line is error-prone and tricky. The logic of the check would have failed to fix these cases:

```java
// The type arguments themselves can have generics
private final ServiceTrackerList<Indexer<?>, Indexer<?>> serviceTrackerList1;

// Newline right after the '<' would break the check
private final ServiceTrackerList<
	CTService, CTService> serviceTrackerList2;
```

For checks like this, writing a `JavaTermCheck` is the better option. `JavaTermCheck` uses a Java parser, so you can perform code searches that are more precise than `BaseFileCheck`. Also, with `JavaTermCheck`, you can target specific parts of Java code (e.g. methods, classes, variables) and not have to deal with the entire file contents. For example, the check only operates on variable declarations (the `doProcess()` processes and returns the contents of variable declarations).

I do have one question for you: can we assume that the type arguments for `ServiceTrackerList` will always be same? For example, is an input case like this possible?: `ServiceTrackerList<CTEventListenerA, CTEventListenerB>`. If it is possible, how do we handle this case? Do we just take the first type argument?

### CODE REVIEW

**Comment by kevhlee** [comment]
@nicolas-sss, for future reference, this is one of the reasons why we want to use `JavaTermCheck` over `FileCheck`.

cc: @natocesarrego

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
Hi @kevhlee.
Answering your question, I researched the portal implementations here and found only one case in which the first argument is different from the second argument, in this case the 7.4 version of this implementation preserved the second argument.
`ServiceTrackerList <S, T>` -> `ServiceTrackerList <T>`

**Comment by kevhlee** [comment]
@michaelmdelcavalcanti, thanks for looking into that!

Based on this, what is the rule for this check? Do we need to always use the 2nd generic type?

**Comment by michaelmdelcavalcanti** [comment]
@kevhlee.
I believe that preserving the second argument is more assertive, in 99% of the cases the two arguments are the same so preserving the first or second argument makes no difference, but if in 1% of the cases the arguments are different and in this case the second argument was preserved, so preserving the second argument will handle all cases. Do you agree?

**Comment by kevhlee** [comment]
Got it, @michaelmdelcavalcanti. Just needed to make sure. If that's the case, then I need to change my work slightly. Also, there seems to be issues running `ci:test` on this PR. So I will rework and resend the PR.

**Comment by kevhlee** [comment]
See <https://github.com/kevhlee/liferay-portal/pull/70>.

**Pull request closed without merging**
