### PR TITLE
LPS-185318 Create a check for the ServiceTrackerList

### PR DESCRIPTION
**Pull request by michaelmdelcavalcanti**
Ticket: [LPS-185318](https://issues.liferay.com/browse/LPS-185318)
Follow-up: https://github.com/brianchandotcom/liferay-portal/pull/135731

### CODE REVIEW

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by michaelmdelcavalcanti** [comment]
cc: @kevhlee

**Comment by kevhlee** [comment]
LGTM. I'm going to manually forward this.

**Comment by kevhlee** [comment]
Manually forwarded here: <https://github.com/brianchandotcom/liferay-portal/pull/135790>

**Pull request closed without merging**
