### PR TITLE
LPS-185740 Update `UpgradeJavaCheck`

### PR DESCRIPTION
**Pull request by kevhlee**
From @michaelmdelcavalcanti,

>Ticket: [LPS-185740](https://issues.liferay.com/browse/LPS-185740)
Hi, Kevin.
Besides adding some more imports to imports.txt, this is an update to UpgradeJavaCheck, now if the classname has been changed, we will try to change all matches of the changed class.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Hi @michaelmdelcavalcanti, great job with this check 🙂! Just made a minor change to the logic and added some SF changes.

cc: @nicolas-sss

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:forward

**Comment by nicolas-sss** [comment]
ci:forward

**Comment by nicolas-sss** [comment]
ci:forward

**Comment by kevhlee** [comment]
Manually forwarded here: <https://github.com/brianchandotcom/liferay-portal/pull/135789>

**Pull request closed without merging**
